spring:
  application:
    name: eureka-ribbon
server:
  port: 8005
eureka:
  client:
    fetchRegistry: true
    service-url:
       defaultZone: http://192.168.31.189:8000/eureka,http://192.168.31.189:9000/eureka

logging:
  config: classpath:logback-boot.xml
  file: ${spring.application.name}